- hosts: localhost
  vars_prompt:
    - name: "mode"
      prompt: "Choose app-only or all."
      default: app-only
      private: no
  # Ansibleの変数はplaybookやrole間で一つの名前空間を共有しているような挙動をするため
  # 作法としてはhostやroleごとに固有のprefixをつけて一意にすべきだが
  # localhostについてはcache_valid_timeなどを個別に定義するのがあまりに冗長だったため
  # あえてhost_varsの変数定義を各roleが直接参照するような形にしている
  roles:
    - { role: sources.list, when: "mode == 'all'" }
    - common_app
    - fish
    - skk
    - { role: python, when: "mode == 'all'" }
    - { role: golang, when: "mode == 'all'" }
    - { role: dotfiles, when: "mode == 'all'" }
    - { role: Myrica, when: "mode == 'all'" }
    - { role: gnome, when: "mode == 'all'" }
    - { role: mount, when: "mode == 'all'" }
