- name: add theme-repository
  become: yes
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - 'ppa:snwh/pulp'

- name: apt install gnome
  become: yes
  apt:
    name: "{{ item.name }}" 
    state: "{{ item.state }}" 
    cache_valid_time: "{{ cache_valid_time }}"
  with_items:
    - { name: gnome-tweaks, state: latest }
    - { name: materia-gtk-theme, state: latest }
    - { name: papirus-icon-theme, state: latest }
    - { name: paper-icon-theme, state: latest }
    - { name: paper-cursor-theme, state: latest }
    # - { name: paper-gtk-theme, state: latest } TODO: 見つからない
    - { name: fonts-ricty-diminished, state: latest }
    - { name: fonts-roboto, state: latest }
    - { name: fonts-mplus, state: latest }

- name: gsettings
  command: gsettings set {{ item }}
  register: gsettings_result
  changed_when: False
  failed_when: gsettings_result.rc not in [0]
  with_items:
    - org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'skk')]"
    - org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
    - org.gnome.desktop.interface clock-show-date true
    - org.gnome.desktop.interface cursor-theme "Paper"
    - org.gnome.desktop.interface document-font-name "Roboto 11"
    - org.gnome.desktop.interface font-name "Roboto 12"
    - org.gnome.desktop.interface gtk-enable-primary-paste false
    - org.gnome.desktop.interface gtk-theme "Materia-compact"
    - org.gnome.desktop.interface icon-theme "Paper"
    - org.gnome.desktop.interface monospace-font-name "M+ 1m 12"
    - org.gnome.desktop.interface show-battery-percentage true
    - org.gnome.desktop.screensaver lock-enabled false
    - org.gnome.desktop.session idle-delay 900
    - org.gnome.desktop.wm.preferences button-layout ":appmenu,minimize,maximize,close"
    - org.gnome.desktop.wm.preferences mouse-button-modifier "<Alt>"
    - org.gnome.desktop.wm.preferences resize-with-right-button true
    - org.gnome.desktop.wm.preferences titlebar-font "Roboto 12"
    - org.gnome.desktop.privacy remove-old-temp-files true
    - org.gnome.desktop.privacy old-files-age 7
    - org.gnome.desktop.privacy remember-recent-files false
    - org.gnome.desktop.privacy recent-files-max-age 1
    - org.gnome.mutter overlay-key 'Super_R'
    - org.gnome.nautilus.desktop trash-icon-visible false
    - org.gnome.nautilus.desktop volumes-visible false
    - org.gnome.nautilus.list-view use-tree-view true
    - org.gnome.nautilus.preferences confirm-trash false
    - org.gnome.nautilus.preferences executable-text-activation 'ask'
    - org.gnome.nautilus.preferences recursive-search 'always'
    - org.gnome.nautilus.preferences show-directory-item-counts 'always'
    - org.gnome.nautilus.preferences show-create-link true
    - org.gnome.nautilus.preferences show-image-thumbnails 'always'
    - org.gnome.settings-daemon.plugins.power power-button-action suspend
    - org.gnome.shell.extensions.dash-to-dock dock-fixed false

- name: replace user-dirs.dirs
  replace:
    path: "{{ user_home }}/.config/user-dirs.dirs"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: yes
  with_items:
    # nautilusのサイドバーで非表示にしたい場合、コメントアウトだとリブート時に復元されてしまうようになった
    # 回避策としてHOMEを指定する
    - { regexp: ^XDG_DOWNLOAD.*, replace: 'XDG_DOWNLOAD_DIR="$HOME"' }
    - { regexp: ^XDG_TEMPLATES.*, replace: 'XDG_TEMPLATES_DIR="$HOME"' }
    - { regexp: ^XDG_PUBLICSHARE.*, replace: 'XDG_PUBLICSHARE_DIR="$HOME"' }
    - { regexp: ^XDG_DOCUMENTS.*, replace: 'XDG_DOCUMENTS_DIR="$HOME"' }
    - { regexp: ^XDG_MUSIC.*, replace: 'XDG_MUSIC_DIR="$HOME"' }
    - { regexp: ^XDG_PICTURES.*, replace: 'XDG_PICTURES_DIR="$HOME"' }
    - { regexp: ^XDG_VIDEOS.*, replace: 'XDG_VIDEOS_DIR="$HOME"' }
